Варіант 20

In [11]:
import numpy as np

1. Створіть одновимірний масив (вектор) з сумами кожного числа та його
попереднього, починаючи з 1, та виведіть його значення.

In [32]:
n = 20
fib = np.zeros(n, dtype=int)
fib[0] = 1
if n > 1:
    fib[1] = 1
for i in range(2, n):
    fib[i] = fib[i-1] + fib[i-2]
print(fib)

[   1    1    2    3    5    8   13   21   34   55   89  144  233  377
  610  987 1597 2584 4181 6765]


2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його значеннями
випадкових дійсних чисел від 1 до 10.

In [13]:
arr = np.random.rand(3, 3)
arr

array([[0.4844443 , 0.94933934, 0.35284262],
       [0.60386116, 0.06346708, 0.87689474],
       [0.38910085, 0.95142823, 0.34149533]])

3. Створіть масив розміром 3x3, заповніть його випадковими натуральними числами від
1 до 100 та виведіть мін значення

In [14]:
arr = np.random.randint(1,100,(3,3))
print(arr)
print(arr.min())

[[32  5 93]
 [11 66 82]
 [80 88  9]]
5


4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в
діапазоні від 0 до 1 та знайдіть кількість елементів, що більше 0.5.

In [15]:
arr = np.random.rand(4, 4)
print(arr)
print(np.sum(arr > 0.5))

[[0.44758544 0.78742746 0.52823116 0.34168353]
 [0.55933953 0.2769579  0.55764543 0.50446006]
 [0.7323315  0.82099006 0.79677452 0.21553055]
 [0.49488581 0.76356774 0.67786479 0.28466768]]
10


5. Створіть два одновимірних масиви розміром 4, заповніть їх випадковими цілими числами від -10 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [30]:
arr1 = np.random.randint(-10, 11, 4)
arr2 = np.random.randint(-10, 11, 4)

print("array 1:")
print(arr1)
print("\narray 2:")
print(arr2)

addition = arr1 + arr2
print("\naddition:")
print(addition)

subtraction = arr1 - arr2
print("\nsubtraction:")
print(subtraction)

multiplication = arr1 * arr2
print("\nmultiplication:")
print(multiplication)

array 1:
[-8 -2 10  7]

array 2:
[-10  -7 -10 -10]

addition:
[-18  -9   0  -3]

subtraction:
[ 2  5 20 17]

multiplication:
[  80   14 -100  -70]


6. Створіть дві матриці 3x3, заповніть їх довільними цілими числами від 1 до 20 та знайдіть їх добуток.

In [34]:
arr1 = np.random.randint(1, 21, (3, 3))
print("array 1:")
print(arr1)

arr2 = np.random.randint(1, 21, (3, 3))
print("\narray 2:")
print(arr2)

multiplication = np.dot(arr1, arr2)
print("\nmultiplication")
print(multiplication)


array 1:
[[ 3 15  1]
 [ 6  7 18]
 [ 7 12 14]]

array 2:
[[15  9 19]
 [ 7 10  2]
 [ 3 12 19]]

multiplication
[[153 189 106]
 [193 340 470]
 [231 351 423]]


7. Створіть дві матриці розміром 2x3 та 3x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 4 та перемножте їх між собою.


In [35]:
arr1 = np.random.randint(1, 5, (2, 3))
print("array 1:")
print(arr1)

arr2 = np.random.randint(1, 5, (3, 3))
print("\narray 2:")
print(arr2)

multiplication = np.dot(arr1, arr2)
print("\nmultiplication")
print(multiplication)

array 1:
[[2 1 1]
 [3 2 2]]

array 2:
[[2 1 3]
 [1 3 1]
 [3 3 3]]

multiplication
[[ 8  8 10]
 [14 15 17]]


8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 7 та знайдіть її обернену матрицю.

In [38]:
arr = np.random.randint(1, 8, (3, 3))
print(arr)

print(np.linalg.inv(arr))

[[1 5 3]
 [4 7 4]
 [2 5 7]]
[[-0.54716981  0.37735849  0.01886792]
 [ 0.37735849 -0.01886792 -0.1509434 ]
 [-0.11320755 -0.09433962  0.24528302]]


9. Створіть матрицю розміром 4x4, заповніть її випадковими цілими числами в діапазоні від 0 до 1 та транспонуйте її.

In [41]:
arr = np.random.randint(0,2, (4, 4))
print(arr)
print(arr.T)

[[0 0 1 0]
 [0 1 0 1]
 [0 1 1 1]
 [1 0 0 0]]
[[0 0 0 1]
 [0 1 1 0]
 [1 0 1 0]
 [0 1 1 0]]


10. Створіть матрицю розміром 3x4 та вектор розміром 4x1, заповніть матрицю випадковими дійсними числами від 0 до 1, а вектор - випадковими дійсними числами від 0 до 1, і знайдіть добуток матриці на вектор.

In [43]:
arr1 = np.random.rand(3, 4)
arr2 = np.random.rand(4, 1)
print(arr1)
print(arr2)

multiplication = np.dot(arr1, arr2)
print("\nmultiplication")
print(multiplication)

[[0.57252306 0.50462542 0.19443989 0.83584632]
 [0.6051792  0.81082684 0.23305838 0.50224729]
 [0.9106388  0.31644776 0.60688513 0.79754611]]
[[0.55113771]
 [0.25210941]
 [0.37487931]
 [0.20039025]]

multiplication
[[0.68314681]
 [0.72596838]
 [0.96899598]]


11. Створіть матрицю розміром 2x3 та вектор розміром 3x1, заповніть матрицю
випадковими дійсними числами від 0 до 1, а вектор - випадковими дійсними числами
від 0 до 1, і знайдіть добуток матриці на вектор.

In [47]:
arr1 = np.random.rand(2, 3)
arr2 = np.random.rand(3, 1)
print(arr1)
print(arr2)

multiplication = np.dot(arr1, arr2)
print("\nmultiplication")
print(multiplication)

[[0.81348771 0.90473931 0.50983472]
 [0.01714963 0.20301059 0.81109946]]
[[0.30092319]
 [0.49844029]
 [0.41905053]]

multiplication
[[0.90940235]
 [0.44624104]]


12. Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в
діапазоні від 1 до 5 та знайдіть добуток елементів діагоналі другої матриці.

In [49]:
arr1 = np.random.randint(1, 6, (3, 3))
arr2 = np.random.randint(1, 6, (3, 3))
print(arr1)
print(arr2)
print(np.prod(np.diag(arr2)))


[[2 5 1]
 [5 2 4]
 [3 4 5]]
[[4 3 2]
 [1 1 3]
 [5 4 5]]
20


13. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в
діапазоні від 1 до 5 та знайдіть різницю їх елементів.

In [50]:
arr1 = np.random.randint(1, 6, (4, 4))
arr2 = np.random.randint(1, 6, (4, 4))
print(arr1)
print(arr2)
print(arr1 - arr2)

[[4 1 5 2]
 [2 2 4 4]
 [5 1 4 3]
 [2 4 2 2]]
[[1 2 2 4]
 [1 1 3 4]
 [1 2 4 2]
 [2 4 5 2]]
[[ 3 -1  3 -2]
 [ 1  1  1  0]
 [ 4 -1  0  1]
 [ 0  0 -3  0]]


14. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні
від 1 до 10 та знайдіть найменший елемент матриці.

In [52]:
arr = np.random.randint(1, 11, (3, 3))
print(arr)
print(np.min(arr))

[[ 1  5  9]
 [ 3  2 10]
 [ 2  9  2]]
1


15. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в
діапазоні від -2 до 2 та знайдіть вектор-стовпчик, що містить кількість ненульових
елементів в кожному рядку матриці.


In [60]:
arr = np.random.randint(-2, 3, (3, 3))
print(arr)
print(np.count_nonzero(arr, axis = 1).reshape(-1,1))

[[ 2 -2  0]
 [ 1  0  1]
 [ 0 -2  0]]
[[2]
 [2]
 [1]]
